-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Aug 27, 2024 at 03:37 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `test`
--

-- --------------------------------------------------------

--
-- Table structure for table `water_conditions_verification`
--

CREATE TABLE `water_conditions_verification` (
  `id` int(11) NOT NULL,
  `lat` float DEFAULT NULL,
  `lng` float DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `ika_score` int(11) DEFAULT NULL,
  `ikaCategories` varchar(50) DEFAULT NULL,
  `lastUpdate` varchar(50) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `reporter_name` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `ika_file` varchar(255) DEFAULT NULL,
  `file_extension` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Dumping data for table `water_conditions_verification`
--

INSERT INTO `water_conditions_verification` (`id`, `lat`, `lng`, `name`, `status`, `ika_score`, `ikaCategories`, `lastUpdate`, `description`, `reporter_name`, `email`, `ika_file`, `file_extension`) VALUES
(1, -6.1461, 106.817, 'Pekojan, Tambora, West Jakarta City, Jakarta', 'verified', 12, 'Good', '8/16/2024 15:04', 'sadsa', 'fadhel-rizanda', 'fadhelbaihaqir25@gmail.com', '1723795497070.xlsx', 'xlsx'),
(3, -6.2088, 106.846, 'Sudirman, Central Jakarta City, Jakarta', 'verified', 75, 'Good', '8/16/2024 14:28', 'ACTIVITY_TEST_PASSWORD___Based on the parameters above, after several calculations of the Water Quality Index (IKA) data available for the Sudirman area, Central Jakarta, on January 15, 2024, the IKA value indicates that the water quality in the area is classified as good with an IKA value of 75.\r\n', 'fadhel-rizanda', 'fadhelbaihaqir25@gmail.com', '1723793300371.xlsx', 'xlsx'),
(4, -6.2146, 106.845, 'Kemayoran, Central Jakarta City, Jakarta', 'verified', 45, 'Moderately Polluted', '20/02/2024 12:00', 'Based on the parameters above, after several calculations of the Water Quality Index (IKA) data available for the Kemayoran area, Central Jakarta, on February 20, 2024, the IKA value indicates that the water quality in the area is classified as moderately polluted with an IKA value of 45.', NULL, NULL, NULL, NULL),
(5, -6.2105, 106.852, 'Cikini, Central Jakarta City, Jakarta', 'verified', 90, 'Good', '7/26/2024 18:57', 'The water in Cikini appears fairly clean, with a slight improvement in quality noted during the dry season. However, during the rainy season, water quality can fluctuate. The presence of some local industries and urban runoff affects the overall water quality. Residents often rely on filtered water for drinking. The community hopes for continuous improvement in water quality to ensure safer and cleaner water for daily use.', 'Fadhel Baihaqi Rizanda', 'test@example.us', NULL, NULL),
(6, -6.1751, 106.865, 'Monas, Central Jakarta City, Jakarta', 'verified', 80, 'Good', '7/26/2024 19:03', 'Based on the parameters above, after several calculations of the Water Quality Index (IKA) data available for the Monas area, Central Jakarta, on January 5, 2024, the IKA value indicates that the water quality in the area is classified as good with an IKA value of 80.', 'Martin Gomez', 'teste@exemplo.us', NULL, NULL),
(7, -6.1754, 106.827, 'Senen, Central Jakarta City, Jakarta', 'unverified', 0, 'Quite Good', '8/13/2024 19:05', 'The water in Senen appears fairly clean, with a slight improvement in quality noted during the dry season. However, during the rainy season, water quality can fluctuate. The presence of some local industries and urban runoff affects the overall water quality. Residents often rely on filtered water for drinking. The community hopes for continuous improvement in water quality to ensure safer and cleaner water for daily use.', 'fadhel-rizanda', 'fadhelbaihaqir25@gmail.com', NULL, NULL),
(8, -6.2001, 106.845, 'Kuningan, South Jakarta City, Jakarta', 'verified', 72, 'Good', '10/02/2024 08:30', 'Based on the parameters above, after several calculations of the Water Quality Index (IKA) data available for the Kuningan area, South Jakarta, on February 10, 2024, the IKA value indicates that the water quality in the area is classified as good with an IKA value of 72.', NULL, NULL, NULL, NULL),
(9, -6.2251, 106.839, 'Tebet, South Jakarta City, Jakarta', 'verified', 48, 'Moderately Polluted', '15/03/2024 11:00', 'Based on the parameters above, after several calculations of the Water Quality Index (IKA) data available for the Tebet area, South Jakarta, on March 15, 2024, the IKA value indicates that the water quality in the area is classified as moderately polluted with an IKA value of 48.', NULL, NULL, NULL, NULL),
(10, -6.1907, 106.823, 'Senayan, Central Jakarta City, Jakarta', 'verified', 38, 'Moderately Polluted', '05/04/2024 14:45', 'Based on the parameters above, after several calculations of the Water Quality Index (IKA) data available for the Senayan area, Central Jakarta, on April 5, 2024, the IKA value indicates that the water quality in the area is classified as moderately polluted with an IKA value of 38.', NULL, NULL, NULL, NULL),
(11, -6.1754, 106.791, 'Pondok Indah, South Jakarta City, Jakarta', 'unverified', NULL, 'Quite Good', '20/05/2024 16:30', 'The water in Pondok Indah appears fairly clean, with a notable improvement in quality compared to previous years. However, water quality can still be affected by seasonal changes and urban runoff. Residents typically use filtered or bottled water for drinking and cooking.', 'Mario Balotelli', 'k@gmail.com', NULL, NULL),
(12, -6.1348, 106.807, 'Ancol, North Jakarta City, Jakarta', 'unverified', NULL, 'Lightly Polluted', '25/06/2024 12:00', 'The water in Ancol is lightly polluted, with occasional reports of discoloration and odors, especially after heavy rains. Despite these issues, the area is popular for recreational activities, and ongoing efforts are being made to improve water quality through better waste management and pollution control.', 'Ucok Sihombing', 'l@gmail.com', NULL, NULL),
(13, -6.1405, 106.785, 'Muara Angke, North Jakarta City, Jakarta', 'verified', 25, 'Heavily Polluted', '05/07/2024 14:00', 'Based on the parameters above, after several calculations of the Water Quality Index (IKA) data available for the Muara Angke area, North Jakarta, on July 5, 2024, the IKA value indicates that the water quality in the area is classified as heavily polluted with an IKA value of 25.', NULL, NULL, NULL, NULL),
(14, -6.1016, 106.837, 'Marunda, North Jakarta City, Jakarta', 'unverified', NULL, 'Heavily Polluted', '10/08/2024 09:30', 'The water in Marunda is extremely polluted, with significant amounts of industrial waste and sewage contributing to poor water quality. The water often appears dark and emits a strong odor, making it unsuitable for any domestic use. Local residents have reported various health issues related to water contamination and are in dire need of clean water sources.', 'Rahmat Selamat', 'n@gmail.com', NULL, NULL),
(15, -6.1774, 106.827, 'Grogol Petamburan, West Jakarta City, Jakarta', 'verified', 65, 'Quite Good', '01/06/2024 10:00', 'Based on the parameters above, after several calculations of the Water Quality Index (IKA) data available for the Grogol Petamburan area, West Jakarta, on June 1, 2024, the IKA value indicates that the water quality in the area is classified as good with an IKA value of 65.', NULL, NULL, NULL, NULL),
(16, -6.1619, 106.843, 'Kebon Jeruk, West Jakarta City, Jakarta', 'unverified', NULL, 'Moderately Polluted', '15/07/2024 14:00', 'The water in Kebon Jeruk is moderately polluted with some issues of turbidity and occasional odor. Improvement efforts are ongoing to enhance water quality.', 'Rina Hapsari', 'p@gmail.com', NULL, NULL),
(17, -6.2032, 106.846, 'Cilandak, South Jakarta City, Jakarta', 'verified', 70, 'Good', '20/06/2024 09:30', 'Based on the parameters above, after several calculations of the Water Quality Index (IKA) data available for the Cilandak area, South Jakarta, on June 20, 2024, the IKA value indicates that the water quality in the area is classified as good with an IKA value of 70.', NULL, NULL, NULL, NULL),
(18, -6.1985, 106.845, 'Kelapa Gading, North Jakarta City, Jakarta', 'verified', 50, 'Moderately Polluted', '05/07/2024 11:00', 'The water quality in Kelapa Gading is currently classified as moderately polluted, which means there are noticeable contaminants present. This pollution is attributed to industrial activities nearby, leading to occasional issues with water quality. Regular monitoring and interventions are necessary to address these pollution sources and improve water safety for residents.', NULL, NULL, NULL, NULL),
(19, -6.1484, 106.786, 'Jatinegara, East Jakarta City, Jakarta', 'unverified', NULL, 'Lightly Polluted', '25/07/2024 16:00', 'Jatinegara\'s water is lightly polluted, indicating a relatively low level of contamination. This situation is primarily caused by local runoff and waste, which can occasionally affect water quality. Efforts are in place to reduce pollution and manage waste better to prevent further deterioration of water conditions.', 'Budi Santoso', 's@gmail.com', NULL, NULL),
(20, -6.1725, 106.823, 'Pasar Minggu, South Jakarta City, Jakarta', 'verified', 68, 'Quite Good', '10/06/2024 12:00', 'In Pasar Minggu, the water quality is considered quite good with an IKA score of 68, reflecting generally clean and safe water. This assessment suggests that the area benefits from effective water management practices and low levels of pollution, making it a relatively safe place for water consumption.', NULL, NULL, NULL, NULL),
(21, -6.1855, 106.824, 'Kramat Jati, East Jakarta City, Jakarta', 'verified', 52, 'Moderately Polluted', '15/05/2024 08:00', 'Kramat Jati\'s water is classified as moderately polluted, with concerns about contamination largely due to local waste and insufficient waste management systems. The area experiences occasional issues with water quality, which necessitates ongoing monitoring and improvements in waste management to enhance water safety.', NULL, NULL, NULL, NULL),
(22, -6.1969, 106.835, 'Tanah Abang, Central Jakarta City, Jakarta', 'unverified', NULL, 'Heavily Polluted', '30/06/2024 15:00', 'The water in Tanah Abang is heavily polluted, reflecting significant problems related to industrial waste and poor water management practices. The pollution levels are high, which poses risks to health and requires substantial interventions to address the sources of contamination and improve overall water quality.', 'Indah Sari', 'v@gmail.com', NULL, NULL),
(23, -6.1797, 106.851, 'Pondok Kopi, East Jakarta City, Jakarta', 'verified', 60, 'Moderately Polluted', '01/07/2024 10:30', 'Pondok Kopi enjoys quite good water quality with an IKA value of 60. This indicates that the area generally has clean water with minimal pollution. Regular monitoring helps maintain these conditions, ensuring that the water remains safe for everyday use.', 'Fadhel Baihaqi Rizanda', 'fadhelbaihaqir25@gmail.com', NULL, NULL),
(24, -6.2176, 106.828, 'Bintaro, South Jakarta City, Jakarta', 'unverified', NULL, 'Quite Good', '15/08/2024 12:00', 'Bintaro\'s water quality is reported as quite good, indicating that the water is relatively clean with low levels of contamination. Periodic monitoring helps maintain these standards, and efforts are made to address any emerging issues to ensure continued water safety.', 'Dina Widiastuti', 'x@gmail.com', NULL, NULL),
(25, -6.208, 106.829, 'Jakarta Selatan, South Jakarta City, Jakarta', 'verified', 73, 'Good', '20/08/2024 09:00', 'The water quality in Jakarta Selatan is assessed as good with an IKA score of 73, suggesting very clean water. This high score reflects effective water management and minimal pollution, contributing to overall health and safety in the area.', NULL, NULL, NULL, NULL),
(26, -6.1397, 106.826, 'Tangerang, Banten', 'unverified', NULL, 'Moderately Polluted', '15/07/2024 14:00', 'Tangerang\'s water is moderately polluted, experiencing issues such as turbidity and occasional odor. The pollution stems from various sources, including local runoff and waste. Ongoing improvement efforts aim to address these issues and enhance water quality for better public health.', 'Dewi Mardiana', 'z@gmail.com', NULL, NULL),
(27, -6.2392, 106.846, 'Cibubur, East Jakarta City, Jakarta', 'verified', 75, 'Good', '7/26/2024 19:29', 'The water quality in Cibubur is rated as quite good with an IKA value of 60. This suggests that the water in this area is generally clean and safe. Regular testing and monitoring ensure that the quality remains high and any potential issues are addressed promptly.', 'Fagfhgfh', 'ejemplo@ejemplo.mx', NULL, NULL),
(28, -6.191, 106.818, 'Kemanggisan, West Jakarta City, Jakarta', 'verified', 52, 'Moderately Polluted', '05/07/2024 11:00', 'Kemanggisan\'s water is moderately polluted, with occasional reports of contamination linked to nearby industrial activities. While the pollution levels are not severe, continued monitoring and mitigation measures are necessary to maintain and improve water quality.', NULL, NULL, NULL, NULL),
(29, -6.2625, 106.789, 'Serpong, South Tangerang, Banten', 'unverified', NULL, 'Lightly Polluted', '25/07/2024 16:00', 'The water in Serpong is lightly polluted, mainly due to local runoff and waste. Although the contamination levels are lower compared to heavily polluted areas, periodic monitoring is essential to manage and reduce pollution effectively.', 'Rizki Nurhadi', 'y@gmail.com', NULL, NULL),
(30, -6.2213, 106.835, 'Pulomas, East Jakarta City, Jakarta', 'verified', 68, 'Quite Good', '10/06/2024 12:00', 'Pulomas has quite good water quality with an IKA score of 68, indicating that the water is generally clean. The area benefits from effective water management practices, which help maintain a high standard of water quality.', NULL, NULL, NULL, NULL),
(31, -6.2398, 106.755, 'Jakarta Barat, West Jakarta City, Jakarta', 'verified', 57, 'Lightly Polluted', '15/05/2024 08:00', 'The water in Jakarta Barat is lightly polluted, with some concerns about contamination due to local waste. However, the pollution levels are relatively low, and ongoing efforts are made to manage waste and monitor water quality to ensure safety.', NULL, NULL, NULL, NULL),
(32, -6.2156, 106.85, 'Pasar Rebo, East Jakarta City, Jakarta', 'unverified', NULL, 'Heavily Polluted', '30/06/2024 15:00', 'Pasar Rebo faces heavy pollution issues, primarily due to industrial waste and inadequate water management practices. The high level of contamination poses significant health risks, and extensive efforts are needed to address the pollution sources and improve water quality.', 'Hani Aulia', 'a@gmail.com', NULL, NULL),
(33, -6.2244, 106.845, 'Kebayoran Lama, South Jakarta City, Jakarta', 'verified', 62, 'Quite Good', '01/07/2024 10:30', 'The water quality in Kebayoran Lama is quite good, with an IKA score of 62. This rating reflects generally clean water, supported by effective monitoring and management practices that help maintain these positive conditions.', NULL, NULL, NULL, NULL),
(34, -6.1706, 106.818, 'Bintaro Jaya, South Tangerang, Banten', 'unverified', NULL, 'Moderately Polluted', '7/24/2024 11:26', 'Bintaro Jaya has a quite good rating for water quality, indicating that the water is generally clean with low levels of pollution. Periodic monitoring helps ensure that water conditions remain satisfactory and that any issues are addressed promptly.', 'Lina Putri', 'c@gmail.com', NULL, NULL),
(35, -6.3505, 106.817, 'Cikarang, Bekasi, West Java', 'unverified', NULL, 'Moderately Polluted', '15/09/2024 14:00', 'The water in Cikarang has moderate pollution levels primarily due to industrial activities and urban runoff. The presence of industrial facilities in the area contributes to contaminants in the water, affecting its quality. Urban runoff, which carries pollutants from roads and construction sites, further exacerbates the pollution. Regular monitoring and effective waste management practices are necessary to mitigate these issues and improve water quality.', 'Siti Nuraini', 'd@gmail.com', NULL, NULL),
(36, -6.1247, 106.83, 'Bandung, West Java', 'verified', 65, 'Quite Good', '01/05/2024 10:00', 'Bandung\'s water quality is generally considered good, with an IKA value indicating clean water. This favorable status is attributed to the city’s efforts in maintaining effective water treatment facilities and managing pollution sources. However, periodic checks are still crucial to ensure that water quality remains high and that any potential contaminants are promptly addressed.', NULL, NULL, NULL, NULL),
(37, -6.2083, 106.845, 'Bekasi, West Java', 'unverified', NULL, 'Moderately Polluted', '25/08/2024 16:00', 'Bekasi experiences moderate pollution levels due to a combination of industrial waste and urban activities. The area\'s industrial growth has led to increased pollutants entering the water systems, affecting water quality. Urban activities, including improper waste disposal and runoff from paved surfaces, contribute to the pollution. Efforts to improve waste management and water treatment infrastructure are essential to mitigate these impacts.', 'Dewi Ayu', 'f@gmail.com', NULL, NULL),
(38, -6.2124, 106.825, 'Depok, West Java', 'verified', 58, 'Lightly Polluted', '05/07/2024 11:00', 'The water quality in Depok is categorized as lightly polluted, which indicates that there are some concerns related to local waste. The pollution levels are relatively low compared to more heavily polluted areas, but issues such as occasional litter and runoff from residential areas can affect water quality. Continuous monitoring and improved waste management practices are important to ensure the water remains safe and clean.', NULL, NULL, NULL, NULL),
(39, -6.3311, 106.811, 'Serang, Banten', 'unverified', NULL, 'Heavily Polluted', '7/26/2024 20:13', 'test_ika___Serang’s water is moderately polluted due to surrounding industrial activities and inadequate waste management practices. Industrial discharges and insufficient treatment of waste contribute to the pollution, affecting water quality. Improving waste management and implementing stricter regulations for industrial discharge are crucial for enhancing the water quality in this area.', 'sadafdad', 'asdasdasa@gmail.com', NULL, NULL),
(40, -6.22, 106.776, 'Cilegon, Banten', 'verified', 42, 'Moderately Polluted', '15/08/2024 08:00', 'Cilegon\'s water quality is moderately polluted, primarily due to issues related to industrial discharges. The high level of industrial activity in the region results in pollutants entering the water supply, which affects its quality. Efforts to enhance waste treatment and control industrial emissions are needed to address these pollution issues and improve overall water quality.', NULL, NULL, NULL, NULL),
(41, -6.0365, 106.729, 'Karawang, West Java', 'verified', 50, 'Moderately Polluted', '01/07/2024 09:00', 'Karawang’s water is moderately polluted, influenced by local industrial activities and agricultural runoff. Industrial processes contribute to the contamination, while runoff from agriculture can introduce additional pollutants. Addressing these sources through improved waste management and better agricultural practices is essential for enhancing water quality in Karawang.', NULL, NULL, NULL, NULL),
(42, -6.3153, 106.741, 'Tangerang Selatan, Banten', 'unverified', NULL, 'Lightly Polluted', '10/07/2024 14:00', 'Tangerang Selatan experiences lightly polluted water, with some issues related to urban runoff and local waste. While the pollution levels are lower compared to more heavily affected areas, maintaining good water quality requires ongoing management of waste and runoff to prevent further degradation.', 'Benny Widodo', 'j@gmail.com', NULL, NULL),
(43, -6.1772, 106.918, 'Jakarta Utara, North Jakarta City, Jakarta', 'unverified', 55, 'Heavily Polluted', '7/24/2024 11:24', 'updated__Jakarta Utara\'s water quality is classified as lightly polluted, reflecting the impact of urban and industrial activities. While the level of pollution is relatively low, ongoing monitoring and management are necessary to address any emerging issues and ensure that water quality remains acceptable.', 'wdwqdqw', 'qwd@gmail.com', NULL, NULL),
(44, -6.052, 106.792, 'Purwakarta, West Java', 'unverified', NULL, 'Quite Good', '15/07/2024 16:00', 'Purwakarta\'s water quality is quite good, although occasional issues related to local waste may arise. The generally clean status of the water reflects effective local management and treatment efforts. Continued vigilance and regular monitoring are essential to address any potential problems and maintain high water quality.', 'Agus Rahmat', 'm@gmail.com', NULL, NULL),
(45, -6.297, 106.787, 'Cikupa, Tangerang, Banten', 'verified', 60, 'Quite Good', '05/08/2024 11:00', 'Cikupa has quite good water quality with an IKA value indicating clean water. The positive status is attributed to effective water management practices and relatively low levels of pollution. Regular monitoring helps ensure that the water quality remains high and that any potential issues are addressed promptly.', NULL, NULL, NULL, NULL),
(48, -6.275, 106.964, ' Harapan Indah Regency Bekasi, West Java, Indonesia', 'verified', 69, 'Quite Good', '7/26/2024 16:46', 'Kualitas air di Harapan Indah Regency sangat bergantung pada sumber air yang digunakan, seperti sumur bor, sungai, atau sistem penyediaan air dari pemerintah. Kualitas fisik air, termasuk kekeruhan, warna, dan bau, menjadi indikator utama; air yang jernih dan tidak berbau menunjukkan kualitas yang baik. Dari segi kualitas kimia, air yang ideal memiliki pH seimbang (sekitar 6.5-8.5) dan rendah kandungan bahan kimia berbahaya seperti logam berat dan nitrat. Selain itu, kualitas mikrobiologi harus diperhatikan, memastikan air bebas dari bakteri patogen seperti E. coli dan koliform total yang dapat membahayakan kesehatan. Kualitas biologis juga penting, di mana pertumbuhan alga yang berlebihan harus dihindari untuk mencegah penurunan kualitas air. Pemantauan rutin dan perawatan sistem penyediaan air oleh pihak berwenang sangat penting untuk menjaga agar kualitas air tetap terjaga dan aman untuk digunakan.', 'Fadhel Baihaqi Rizanda', 'fadhelbaihaqir25@gmail.com', NULL, NULL),
(50, -6.1325, 106.875, 'Papanggo Tanjung Priok, North Jakarta City, Jakarta', 'unverified', NULL, 'Good', '7/24/2024 14:49', 'Kualitas air di Harapan Indah Regency sangat bergantung pada sumber air yang digunakan, seperti sumur bor, sungai, atau sistem penyediaan air dari pemerintah. Kualitas fisik air, termasuk kekeruhan, warna, dan bau, menjadi indikator utama; air yang jernih dan tidak berbau menunjukkan kualitas yang baik. Dari segi kualitas kimia, air yang ideal memiliki pH seimbang (sekitar 6.5-8.5) dan rendah kandungan bahan kimia berbahaya seperti logam berat dan nitrat. Selain itu, kualitas mikrobiologi harus diperhatikan, memastikan air bebas dari bakteri patogen seperti E. coli dan koliform total yang dapat membahayakan kesehatan. Kualitas biologis juga penting, di mana pertumbuhan alga yang berlebihan harus dihindari untuk mencegah penurunan kualitas air. Pemantauan rutin dan perawatan sistem penyediaan air oleh pihak berwenang sangat penting untuk menjaga agar kualitas air tetap terjaga dan aman untuk digunakan.', 'Fadhel Baihaqi Rizanda', 'test@example.us', NULL, NULL),
(53, -6.2197, 107, 'Binus', 'unverified', 0, 'Good', '8/22/2024 08:41', 'test3', 'admin123', 'admin123@admin.com', NULL, NULL),
(54, -6.7028, 106.999, 'Puncak, Ciloto, Cipanas, Cianjur Regency, West Java', 'verified', 79, 'Good', '8/13/2024 17:02', 'test', 'Fadhel Baihaqi Rizanda', 'fadhelbaihaqir25@gmail.com', NULL, NULL),
(86, -6.18282, 106.979, 'Bekasi', 'unverified', 0, 'Good', '8/27/2024 20:21', 'test_data', 'testVaryLocation', 'test@example.us', NULL, NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `water_conditions_verification`
--
ALTER TABLE `water_conditions_verification`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `water_conditions_verification`
--
ALTER TABLE `water_conditions_verification`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=87;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
